### PR TITLE
fix: argv not passed to function config in all scenarios

### LINKED ISSUE #11: Webpack function config is not called with CLI arguments
In https://github.com/webpack-contrib/config-loader#gotchas it is specified that webpack function will be called with `argv` parameter, but it does not actually work. There is related issue webpack-contrib/webpack-command#23.

* Operating System: Windows 10
* Node Version: 9.11.1
* NPM Version: 5.6.0
* webpack Version: 4.10.0
* config-loader Version: 1.0.0

### Expected Behavior

Function should be called with arguments passed to CLI.

### Actual Behavior
Function is called without arguments.

### Code

```js
module.exports = function (argv) {
  const production = argv.mode === 'production'
  ...
}
```

### How Do We Reproduce?

Export function from webpack config that uses argv parameter.

### PR DESCRIPTION
**Pull request by shellscape**
This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [x] **test update** 
- [ ] **typo fix**
- [x] **metadata update**

### Motivation / Use-Case

Fixes #11. `argv` wasn't being passed to function configs in all scenarios. 

### Breaking Changes

None

### Additional Info

I wrestled with the question of whether or not to parse `process.argv` in this module, or require consuming modules to pass `argv`. Ultimately passing `argv` would result in a lot of duplicated code among consumers of `config-loader`. I structured the code update to _allow `argv` to be passed in the future_ by treating it like a parameter with a default value, while this is given more thought. But the change fixes the bug immediately for users with no immediate downside. (That approach also has the added benefit of granular test ability).

### CODE REVIEW

File: lib/resolve.js [hunk 1]
```diff
@@ -1,3 +1,5 @@
+const minimist = require('minimist');
```
Comment (evilebottnawi) [inline lib/resolve.js]: Looks good, i think better use `yargs` instead `minimist`, he is deprecated and abandoned (it was said contributor of `minimist`)

Comment (shellscape) [reply lib/resolve.js]: minimist is WAY smaller than yargs and it's very stable for this purpose in its last release (1.2.0). keeping this is OK
